### ISSUE TITLE
Sample file from Aqualog to consider for readEEM {EEM}

### ISSUE THREAD

**Issue by markjohnsonubc** [chengvt/EEM#1]
Submitting an example Aqualog output EEM as .xlsx since .dat are not supported for upload. Thanks for developing this package and for considering including support of Aqualog files for it.

[Week1_Algodao_400_1_Waterfall Plot Sample.xlsx](https://github.com/chengvt/EEM/files/49378/Week1_Algodao_400_1_Waterfall.Plot.Sample.xlsx)

**Comment by chengvt** [comment]
Do you have some raw .dat files? I will try and see if I can add support for it.

**Comment by markjohnsonubc** [comment]
Here is one. Let me know if you would like others.
cheers
Mark

On Dec 1, 2015, at 8:39 PM, chengvt <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you have some raw .dat files? I will try and see if I can add support for it.

�

**Comment by chengvt** [comment]
Thanks! But for some reasons I am not seeing any attached file. Could you check?

**Comment by markjohnsonubc** [comment]
I've put a couple raw output files (.dat) on dropbox at https://www.dropbox.com/sh/2qhblkthbtyf5ro/AAAkGF91skjUQNKT9tHvX4tLa?dl=0

On Dec 1, 2015, at 9:05 PM, chengvt <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks! But for some reasons I am not seeing any attached file. Could you check?

**Comment by chengvt** [comment]
I modified `readEEM` so that it will read AquaLog's files. You can try by reinstalling the develop branch of the package.

```
library(devtools)
install_github("chengvt/EEM", dependencies = TRUE, ref = "develop")
```

However, due to inconsistency between the spacing of wavelengths, `drawEEM` is not working for this data. I hope to be able to look into it during the weekends. Pull request is also welcome. 

Anyway, I have heard that AquaLog put all the samples into one single .dat file. If this is really the case, then `readEEM` will not work for multiple samples. If so I will probably create a new function for importing AquaLog.

**Comment by markjohnsonubc** [comment]
In my experience, Aqualog allows batch exporting of multiple samples, but each is an individual .dat file (not multiple samples bundled into one single .dat).

On Dec 1, 2015, at 11:55 PM, chengvt <notifications@github.com<mailto:notifications@github.com>> wrote:

I modified readEEM so that it will read AquaLog's files. You can try by reinstalling the develop branch of the package.

library(devtools)
install_github("chengvt/EEM", dependencies = TRUE, ref = "develop")

However, due to inconsistency between the spacing of wavelengths, drawEEM is not working for this data. I hope to be able to look into it during the weekends. Pull request is also welcome.

Anyway, I have heard that AquaLog put all the samples into one single .dat file. If this is really the case, then readEEM will not work for multiple samples. If so I will probably create a new function for importing AquaLog.

**Comment by chengvt** [comment]
Then I guess it should work. Please let me know if there is any other problem.

**Comment by chengvt** [comment]
I found the reason why `drawEEM` didn't work with aqualog data. Turned out it's not about the even spacing but rather the decreasing order of the wavelength value. I edited `readEEM` part and now `drawEEM` should work fine with aqualog data. `drawEEMgg` is also available now where ggplot2 was used instead of `filled.contour` in `drawEEM`.
